import mysql.connector

# Database connection setup
db = mysql.connector.connect(
    host="localhost",
    user="root",
    password="",
    database="research_genai"
)
cursor = db.cursor()

# Query to fetch authors meeting criteria
cursor.execute("""
    SELECT id
    FROM oa_authors
    WHERE count_first_before_gpt > 0 AND count_first_after_gpt > 0
""")
authors = cursor.fetchall()

# Function to calculate and insert metrics
def calculate_and_insert_metrics(author_id, date_condition, target_table):
    # Query to fetch metrics from both paper_metrics and paper_metrics_taaco
    query = f"""
        SELECT 
            COUNT(p.paper_id) AS paper_count,
            AVG(pm.word_count) AS avg_word_count,
            AVG(pm.sentence_count) AS avg_sentence_count,
            AVG(pm.avg_sentence_length) AS avg_sentence_length,
            AVG(pm.type_token_ratio) AS avg_type_token_ratio,
            AVG(pm.flesch_reading_ease) AS avg_flesch_reading_ease,
            AVG(pm.flesch_kincaid_grade) AS avg_flesch_kincaid_grade,
            AVG(pm.gunning_fog) AS avg_gunning_fog,
            -- Metrics from paper_metrics_taaco
            AVG(pt.lemma_ttr) AS avg_lemma_ttr,
            AVG(pt.lemma_mattr) AS avg_lemma_mattr,
            AVG(pt.lexical_density_tokens) AS avg_lexical_density_tokens,
            AVG(pt.lexical_density_types) AS avg_lexical_density_types,
            AVG(pt.content_ttr) AS avg_content_ttr,
            AVG(pt.function_ttr) AS avg_function_ttr,
            AVG(pt.function_mattr) AS avg_function_mattr,
            AVG(pt.noun_ttr) AS avg_noun_ttr,
            AVG(pt.verb_ttr) AS avg_verb_ttr,
            AVG(pt.adj_ttr) AS avg_adj_ttr,
            AVG(pt.adv_ttr) AS avg_adv_ttr,
            AVG(pt.prp_ttr) AS avg_prp_ttr,
            AVG(pt.argument_ttr) AS avg_argument_ttr,
            AVG(pt.bigram_lemma_ttr) AS avg_bigram_lemma_ttr,
            AVG(pt.trigram_lemma_ttr) AS avg_trigram_lemma_ttr,
            AVG(pt.adjacent_overlap_all_sent) AS avg_adjacent_overlap_all_sent,
            AVG(pt.adjacent_overlap_all_sent_div_seg) AS avg_adjacent_overlap_all_sent_div_seg,
            AVG(pt.adjacent_overlap_binary_all_sent) AS avg_adjacent_overlap_binary_all_sent,
            AVG(pt.adjacent_overlap_2_all_sent) AS avg_adjacent_overlap_2_all_sent,
            AVG(pt.adjacent_overlap_2_all_sent_div_seg) AS avg_adjacent_overlap_2_all_sent_div_seg,
            AVG(pt.adjacent_overlap_binary_2_all_sent) AS avg_adjacent_overlap_binary_2_all_sent,
            AVG(pt.adjacent_overlap_cw_sent) AS avg_adjacent_overlap_cw_sent,
            AVG(pt.adjacent_overlap_cw_sent_div_seg) AS avg_adjacent_overlap_cw_sent_div_seg,
            AVG(pt.adjacent_overlap_binary_cw_sent) AS avg_adjacent_overlap_binary_cw_sent,
            AVG(pt.adjacent_overlap_2_cw_sent) AS avg_adjacent_overlap_2_cw_sent,
            AVG(pt.adjacent_overlap_2_cw_sent_div_seg) AS avg_adjacent_overlap_2_cw_sent_div_seg,
            AVG(pt.adjacent_overlap_binary_2_cw_sent) AS avg_adjacent_overlap_binary_2_cw_sent,
            AVG(pt.adjacent_overlap_fw_sent) AS avg_adjacent_overlap_fw_sent,
            AVG(pt.adjacent_overlap_fw_sent_div_seg) AS avg_adjacent_overlap_fw_sent_div_seg,
            AVG(pt.adjacent_overlap_binary_fw_sent) AS avg_adjacent_overlap_binary_fw_sent,
            AVG(pt.adjacent_overlap_2_fw_sent) AS avg_adjacent_overlap_2_fw_sent,
            AVG(pt.adjacent_overlap_2_fw_sent_div_seg) AS avg_adjacent_overlap_2_fw_sent_div_seg,
            AVG(pt.adjacent_overlap_binary_2_fw_sent) AS avg_adjacent_overlap_binary_2_fw_sent,
            AVG(pt.adjacent_overlap_noun_sent) AS avg_adjacent_overlap_noun_sent,
            AVG(pt.adjacent_overlap_noun_sent_div_seg) AS avg_adjacent_overlap_noun_sent_div_seg,
            AVG(pt.adjacent_overlap_binary_noun_sent) AS avg_adjacent_overlap_binary_noun_sent,
            AVG(pt.adjacent_overlap_2_noun_sent) AS avg_adjacent_overlap_2_noun_sent,
            AVG(pt.adjacent_overlap_2_noun_sent_div_seg) AS avg_adjacent_overlap_2_noun_sent_div_seg,
            AVG(pt.adjacent_overlap_binary_2_noun_sent) AS avg_adjacent_overlap_binary_2_noun_sent,
            AVG(pt.adjacent_overlap_verb_sent) AS avg_adjacent_overlap_verb_sent,
            AVG(pt.adjacent_overlap_verb_sent_div_seg) AS avg_adjacent_overlap_verb_sent_div_seg,
            AVG(pt.adjacent_overlap_binary_verb_sent) AS avg_adjacent_overlap_binary_verb_sent,
            AVG(pt.adjacent_overlap_2_verb_sent) AS avg_adjacent_overlap_2_verb_sent,
            AVG(pt.adjacent_overlap_2_verb_sent_div_seg) AS avg_adjacent_overlap_2_verb_sent_div_seg,
            AVG(pt.adjacent_overlap_binary_2_verb_sent) AS avg_adjacent_overlap_binary_2_verb_sent,
            AVG(pt.adjacent_overlap_adj_sent) AS avg_adjacent_overlap_adj_sent,
            AVG(pt.adjacent_overlap_adj_sent_div_seg) AS avg_adjacent_overlap_adj_sent_div_seg,
            AVG(pt.adjacent_overlap_binary_adj_sent) AS avg_adjacent_overlap_binary_adj_sent,
            AVG(pt.adjacent_overlap_2_adj_sent) AS avg_adjacent_overlap_2_adj_sent,
            AVG(pt.adjacent_overlap_2_adj_sent_div_seg) AS avg_adjacent_overlap_2_adj_sent_div_seg,
            AVG(pt.adjacent_overlap_binary_2_adj_sent) AS avg_adjacent_overlap_binary_2_adj_sent,
            AVG(pt.adjacent_overlap_adv_sent) AS avg_adjacent_overlap_adv_sent,
            AVG(pt.adjacent_overlap_adv_sent_div_seg) AS avg_adjacent_overlap_adv_sent_div_seg,
            AVG(pt.adjacent_overlap_binary_adv_sent) AS avg_adjacent_overlap_binary_adv_sent,
            AVG(pt.adjacent_overlap_2_adv_sent) AS avg_adjacent_overlap_2_adv_sent,
            AVG(pt.adjacent_overlap_2_adv_sent_div_seg) AS avg_adjacent_overlap_2_adv_sent_div_seg,
            AVG(pt.adjacent_overlap_binary_2_adv_sent) AS avg_adjacent_overlap_binary_2_adv_sent,
            AVG(pt.adjacent_overlap_pronoun_sent) AS avg_adjacent_overlap_pronoun_sent,
            AVG(pt.adjacent_overlap_pronoun_sent_div_seg) AS avg_adjacent_overlap_pronoun_sent_div_seg,
            AVG(pt.adjacent_overlap_binary_pronoun_sent) AS avg_adjacent_overlap_binary_pronoun_sent,
            AVG(pt.adjacent_overlap_2_pronoun_sent) AS avg_adjacent_overlap_2_pronoun_sent,
            AVG(pt.adjacent_overlap_2_pronoun_sent_div_seg) AS avg_adjacent_overlap_2_pronoun_sent_div_seg,
            AVG(pt.adjacent_overlap_binary_2_pronoun_sent) AS avg_adjacent_overlap_binary_2_pronoun_sent,
            AVG(pt.adjacent_overlap_argument_sent) AS avg_adjacent_overlap_argument_sent,
            AVG(pt.adjacent_overlap_argument_sent_div_seg) AS avg_adjacent_overlap_argument_sent_div_seg,
            AVG(pt.adjacent_overlap_binary_argument_sent) AS avg_adjacent_overlap_binary_argument_sent,
            AVG(pt.adjacent_overlap_2_argument_sent) AS avg_adjacent_overlap_2_argument_sent,
            AVG(pt.adjacent_overlap_2_argument_sent_div_seg) AS avg_adjacent_overlap_2_argument_sent_div_seg,
            AVG(pt.adjacent_overlap_binary_2_argument_sent) AS avg_adjacent_overlap_binary_2_argument_sent,
            AVG(pt.adjacent_overlap_all_para) AS avg_adjacent_overlap_all_para,
            AVG(pt.adjacent_overlap_all_para_div_seg) AS avg_adjacent_overlap_all_para_div_seg,
            AVG(pt.adjacent_overlap_binary_all_para) AS avg_adjacent_overlap_binary_all_para,
            AVG(pt.adjacent_overlap_2_all_para) AS avg_adjacent_overlap_2_all_para,
            AVG(pt.adjacent_overlap_2_all_para_div_seg) AS avg_adjacent_overlap_2_all_para_div_seg,
            AVG(pt.adjacent_overlap_binary_2_all_para) AS avg_adjacent_overlap_binary_2_all_para,
            AVG(pt.adjacent_overlap_cw_para) AS avg_adjacent_overlap_cw_para,
            AVG(pt.adjacent_overlap_cw_para_div_seg) AS avg_adjacent_overlap_cw_para_div_seg,
            AVG(pt.adjacent_overlap_binary_cw_para) AS avg_adjacent_overlap_binary_cw_para,
            AVG(pt.adjacent_overlap_2_cw_para) AS avg_adjacent_overlap_2_cw_para,
            AVG(pt.adjacent_overlap_2_cw_para_div_seg) AS avg_adjacent_overlap_2_cw_para_div_seg,
            AVG(pt.adjacent_overlap_binary_2_cw_para) AS avg_adjacent_overlap_binary_2_cw_para,
            AVG(pt.adjacent_overlap_fw_para) AS avg_adjacent_overlap_fw_para,
            AVG(pt.adjacent_overlap_fw_para_div_seg) AS avg_adjacent_overlap_fw_para_div_seg,
            AVG(pt.adjacent_overlap_binary_fw_para) AS avg_adjacent_overlap_binary_fw_para,
            AVG(pt.adjacent_overlap_2_fw_para) AS avg_adjacent_overlap_2_fw_para,
            AVG(pt.adjacent_overlap_2_fw_para_div_seg) AS avg_adjacent_overlap_2_fw_para_div_seg,
            AVG(pt.adjacent_overlap_binary_2_fw_para) AS avg_adjacent_overlap_binary_2_fw_para,
            AVG(pt.adjacent_overlap_noun_para) AS avg_adjacent_overlap_noun_para,
            AVG(pt.adjacent_overlap_noun_para_div_seg) AS avg_adjacent_overlap_noun_para_div_seg,
            AVG(pt.adjacent_overlap_binary_noun_para) AS avg_adjacent_overlap_binary_noun_para,
            AVG(pt.adjacent_overlap_2_noun_para) AS avg_adjacent_overlap_2_noun_para,
            AVG(pt.adjacent_overlap_2_noun_para_div_seg) AS avg_adjacent_overlap_2_noun_para_div_seg,
            AVG(pt.adjacent_overlap_binary_2_noun_para) AS avg_adjacent_overlap_binary_2_noun_para,
            AVG(pt.adjacent_overlap_verb_para) AS avg_adjacent_overlap_verb_para,
            AVG(pt.adjacent_overlap_verb_para_div_seg) AS avg_adjacent_overlap_verb_para_div_seg,
            AVG(pt.adjacent_overlap_binary_verb_para) AS avg_adjacent_overlap_binary_verb_para,
            AVG(pt.adjacent_overlap_2_verb_para) AS avg_adjacent_overlap_2_verb_para,
            AVG(pt.adjacent_overlap_2_verb_para_div_seg) AS avg_adjacent_overlap_2_verb_para_div_seg,
            AVG(pt.adjacent_overlap_binary_2_verb_para) AS avg_adjacent_overlap_binary_2_verb_para,
            AVG(pt.adjacent_overlap_adj_para) AS avg_adjacent_overlap_adj_para,
            AVG(pt.adjacent_overlap_adj_para_div_seg) AS avg_adjacent_overlap_adj_para_div_seg,
            AVG(pt.adjacent_overlap_binary_adj_para) AS avg_adjacent_overlap_binary_adj_para,
            AVG(pt.adjacent_overlap_2_adj_para) AS avg_adjacent_overlap_2_adj_para,
            AVG(pt.adjacent_overlap_2_adj_para_div_seg) AS avg_adjacent_overlap_2_adj_para_div_seg,
            AVG(pt.adjacent_overlap_binary_2_adj_para) AS avg_adjacent_overlap_binary_2_adj_para,
            AVG(pt.adjacent_overlap_adv_para) AS avg_adjacent_overlap_adv_para,
            AVG(pt.adjacent_overlap_adv_para_div_seg) AS avg_adjacent_overlap_adv_para_div_seg,
            AVG(pt.adjacent_overlap_binary_adv_para) AS avg_adjacent_overlap_binary_adv_para,
            AVG(pt.adjacent_overlap_2_adv_para) AS avg_adjacent_overlap_2_adv_para,
            AVG(pt.adjacent_overlap_2_adv_para_div_seg) AS avg_adjacent_overlap_2_adv_para_div_seg,
            AVG(pt.adjacent_overlap_binary_2_adv_para) AS avg_adjacent_overlap_binary_2_adv_para,
            AVG(pt.adjacent_overlap_pronoun_para) AS avg_adjacent_overlap_pronoun_para,
            AVG(pt.adjacent_overlap_pronoun_para_div_seg) AS avg_adjacent_overlap_pronoun_para_div_seg,
            AVG(pt.adjacent_overlap_binary_pronoun_para) AS avg_adjacent_overlap_binary_pronoun_para,
            AVG(pt.adjacent_overlap_2_pronoun_para) AS avg_adjacent_overlap_2_pronoun_para,
            AVG(pt.adjacent_overlap_2_pronoun_para_div_seg) AS avg_adjacent_overlap_2_pronoun_para_div_seg,
            AVG(pt.adjacent_overlap_binary_2_pronoun_para) AS avg_adjacent_overlap_binary_2_pronoun_para,
            AVG(pt.adjacent_overlap_argument_para) AS avg_adjacent_overlap_argument_para,
            AVG(pt.adjacent_overlap_argument_para_div_seg) AS avg_adjacent_overlap_argument_para_div_seg,
            AVG(pt.adjacent_overlap_binary_argument_para) AS avg_adjacent_overlap_binary_argument_para,
            AVG(pt.adjacent_overlap_2_argument_para) AS avg_adjacent_overlap_2_argument_para,
            AVG(pt.adjacent_overlap_2_argument_para_div_seg) AS avg_adjacent_overlap_2_argument_para_div_seg,
            AVG(pt.adjacent_overlap_binary_2_argument_para) AS avg_adjacent_overlap_binary_2_argument_para,
            AVG(pt.syn_overlap_sent_noun) AS avg_syn_overlap_sent_noun,
            AVG(pt.syn_overlap_sent_verb) AS avg_syn_overlap_sent_verb,
            AVG(pt.syn_overlap_para_noun) AS avg_syn_overlap_para_noun,
            AVG(pt.syn_overlap_para_verb) AS avg_syn_overlap_para_verb,
            AVG(pt.lsa_1_all_sent) AS avg_lsa_1_all_sent,
            AVG(pt.lsa_2_all_sent) AS avg_lsa_2_all_sent,
            AVG(pt.lsa_1_all_para) AS avg_lsa_1_all_para,
            AVG(pt.lsa_2_all_para) AS avg_lsa_2_all_para,
            AVG(pt.lda_1_all_sent) AS avg_lda_1_all_sent,
            AVG(pt.lda_2_all_sent) AS avg_lda_2_all_sent,
            AVG(pt.lda_1_all_para) AS avg_lda_1_all_para,
            AVG(pt.lda_2_all_para) AS avg_lda_2_all_para,
            AVG(pt.word2vec_1_all_sent) AS avg_word2vec_1_all_sent,
            AVG(pt.word2vec_2_all_sent) AS avg_word2vec_2_all_sent,
            AVG(pt.word2vec_1_all_para) AS avg_word2vec_1_all_para,
            AVG(pt.word2vec_2_all_para) AS avg_word2vec_2_all_para,
            AVG(pt.basic_connectives) AS avg_basic_connectives,
            AVG(pt.conjunctions) AS avg_conjunctions,
            AVG(pt.disjunctions) AS avg_disjunctions,
            AVG(pt.lexical_subordinators) AS avg_lexical_subordinators,
            AVG(pt.coordinating_conjuncts) AS avg_coordinating_conjuncts,
            AVG(pt.addition) AS avg_addition,
            AVG(pt.sentence_linking) AS avg_sentence_linking,
            AVG(pt.the_order) AS avg_the_order,
            AVG(pt.reason_and_purpose) AS avg_reason_and_purpose,
            AVG(pt.all_causal) AS avg_all_causal,
            AVG(pt.positive_causal) AS avg_positive_causal,
            AVG(pt.opposition) AS avg_opposition,
            AVG(pt.determiners) AS avg_determiners,
            AVG(pt.all_demonstratives) AS avg_all_demonstratives,
            AVG(pt.attended_demonstratives) AS avg_attended_demonstratives,
            AVG(pt.unattended_demonstratives) AS avg_unattended_demonstratives,
            AVG(pt.all_additive) AS avg_all_additive,
            AVG(pt.all_logical) AS avg_all_logical,
            AVG(pt.positive_logical) AS avg_positive_logical,
            AVG(pt.negative_logical) AS avg_negative_logical,
            AVG(pt.all_temporal) AS avg_all_temporal,
            AVG(pt.positive_intentional) AS avg_positive_intentional,
            AVG(pt.all_positive) AS avg_all_positive,
            AVG(pt.all_negative) AS avg_all_negative,
            AVG(pt.all_connective) AS avg_all_connective,
            AVG(pt.pronoun_density) AS avg_pronoun_density,
            AVG(pt.pronoun_noun_ratio) AS avg_pronoun_noun_ratio,
            AVG(pt.repeated_content_lemmas) AS avg_repeated_content_lemmas,
            AVG(pt.repeated_content_and_pronoun_lemmas) AS avg_repeated_content_and_pronoun_lemmas
        FROM paper p
        JOIN paper_oa_author pa ON p.paper_id = pa.paper_id
        JOIN paper_metrics pm ON p.paper_id = pm.paper_id
        JOIN paper_metrics_taaco pt ON p.paper_id = pt.paper_id
        WHERE pa.author_id = %s
          AND pa.author_position = 'first'
          AND p.date_published {date_condition}
          AND p.downloaded = 1
    """
    #print(query, author_id)
    #exit()
    cursor.execute(query, (author_id,))
    result = cursor.fetchone()
    
    # Skip authors with no papers meeting the condition
    paper_count = result[0]
    if paper_count > 0:
        # Insert the calculated metrics into the target table
        insert_query = f"""
            INSERT INTO {target_table} (
                author_id,
                paper_count,
                avg_word_count,
                avg_sentence_count,
                avg_sentence_length,
                avg_type_token_ratio,
                avg_flesch_reading_ease,
                avg_flesch_kincaid_grade,
                avg_gunning_fog,
                avg_lemma_ttr,
                avg_lemma_mattr,
                avg_lexical_density_tokens,
                avg_lexical_density_types,
                avg_content_ttr,
                avg_function_ttr,
                avg_function_mattr,
                avg_noun_ttr,
                avg_verb_ttr,
                avg_adj_ttr,
                avg_adv_ttr,
                avg_prp_ttr,
                avg_argument_ttr,
                avg_bigram_lemma_ttr,
                avg_trigram_lemma_ttr,
                avg_adjacent_overlap_all_sent,
                avg_adjacent_overlap_all_sent_div_seg,
                avg_adjacent_overlap_binary_all_sent,
                avg_adjacent_overlap_2_all_sent,
                avg_adjacent_overlap_2_all_sent_div_seg,
                avg_adjacent_overlap_binary_2_all_sent,
                avg_adjacent_overlap_cw_sent,
                avg_adjacent_overlap_cw_sent_div_seg,
                avg_adjacent_overlap_binary_cw_sent,
                avg_adjacent_overlap_2_cw_sent,
                avg_adjacent_overlap_2_cw_sent_div_seg,
                avg_adjacent_overlap_binary_2_cw_sent,
                avg_adjacent_overlap_fw_sent,
                avg_adjacent_overlap_fw_sent_div_seg,
                avg_adjacent_overlap_binary_fw_sent,
                avg_adjacent_overlap_2_fw_sent,
                avg_adjacent_overlap_2_fw_sent_div_seg,
                avg_adjacent_overlap_binary_2_fw_sent,
                avg_adjacent_overlap_noun_sent,
                avg_adjacent_overlap_noun_sent_div_seg,
                avg_adjacent_overlap_binary_noun_sent,
                avg_adjacent_overlap_2_noun_sent,
                avg_adjacent_overlap_2_noun_sent_div_seg,
                avg_adjacent_overlap_binary_2_noun_sent,
                avg_adjacent_overlap_verb_sent,
                avg_adjacent_overlap_verb_sent_div_seg,
                avg_adjacent_overlap_binary_verb_sent,
                avg_adjacent_overlap_2_verb_sent,
                avg_adjacent_overlap_2_verb_sent_div_seg,
                avg_adjacent_overlap_binary_2_verb_sent,
                avg_adjacent_overlap_adj_sent,
                avg_adjacent_overlap_adj_sent_div_seg,
                avg_adjacent_overlap_binary_adj_sent,
                avg_adjacent_overlap_2_adj_sent,
                avg_adjacent_overlap_2_adj_sent_div_seg,
                avg_adjacent_overlap_binary_2_adj_sent,
                avg_adjacent_overlap_adv_sent,
                avg_adjacent_overlap_adv_sent_div_seg,
                avg_adjacent_overlap_binary_adv_sent,
                avg_adjacent_overlap_2_adv_sent,
                avg_adjacent_overlap_2_adv_sent_div_seg,
                avg_adjacent_overlap_binary_2_adv_sent,
                avg_adjacent_overlap_pronoun_sent,
                avg_adjacent_overlap_pronoun_sent_div_seg,
                avg_adjacent_overlap_binary_pronoun_sent,
                avg_adjacent_overlap_2_pronoun_sent,
                avg_adjacent_overlap_2_pronoun_sent_div_seg,
                avg_adjacent_overlap_binary_2_pronoun_sent,
                avg_adjacent_overlap_argument_sent,
                avg_adjacent_overlap_argument_sent_div_seg,
                avg_adjacent_overlap_binary_argument_sent,
                avg_adjacent_overlap_2_argument_sent,
                avg_adjacent_overlap_2_argument_sent_div_seg,
                avg_adjacent_overlap_binary_2_argument_sent,
                avg_adjacent_overlap_all_para,
                avg_adjacent_overlap_all_para_div_seg,
                avg_adjacent_overlap_binary_all_para,
                avg_adjacent_overlap_2_all_para,
                avg_adjacent_overlap_2_all_para_div_seg,
                avg_adjacent_overlap_binary_2_all_para,
                avg_adjacent_overlap_cw_para,
                avg_adjacent_overlap_cw_para_div_seg,
                avg_adjacent_overlap_binary_cw_para,
                avg_adjacent_overlap_2_cw_para,
                avg_adjacent_overlap_2_cw_para_div_seg,
                avg_adjacent_overlap_binary_2_cw_para,
                avg_adjacent_overlap_fw_para,
                avg_adjacent_overlap_fw_para_div_seg,
                avg_adjacent_overlap_binary_fw_para,
                avg_adjacent_overlap_2_fw_para,
                avg_adjacent_overlap_2_fw_para_div_seg,
                avg_adjacent_overlap_binary_2_fw_para,
                avg_adjacent_overlap_noun_para,
                avg_adjacent_overlap_noun_para_div_seg,
                avg_adjacent_overlap_binary_noun_para,
                avg_adjacent_overlap_2_noun_para,
                avg_adjacent_overlap_2_noun_para_div_seg,
                avg_adjacent_overlap_binary_2_noun_para,
                avg_adjacent_overlap_verb_para,
                avg_adjacent_overlap_verb_para_div_seg,
                avg_adjacent_overlap_binary_verb_para,
                avg_adjacent_overlap_2_verb_para,
                avg_adjacent_overlap_2_verb_para_div_seg,
                avg_adjacent_overlap_binary_2_verb_para,
                avg_adjacent_overlap_adj_para,
                avg_adjacent_overlap_adj_para_div_seg,
                avg_adjacent_overlap_binary_adj_para,
                avg_adjacent_overlap_2_adj_para,
                avg_adjacent_overlap_2_adj_para_div_seg,
                avg_adjacent_overlap_binary_2_adj_para,
                avg_adjacent_overlap_adv_para,
                avg_adjacent_overlap_adv_para_div_seg,
                avg_adjacent_overlap_binary_adv_para,
                avg_adjacent_overlap_2_adv_para,
                avg_adjacent_overlap_2_adv_para_div_seg,
                avg_adjacent_overlap_binary_2_adv_para,
                avg_adjacent_overlap_pronoun_para,
                avg_adjacent_overlap_pronoun_para_div_seg,
                avg_adjacent_overlap_binary_pronoun_para,
                avg_adjacent_overlap_2_pronoun_para,
                avg_adjacent_overlap_2_pronoun_para_div_seg,
                avg_adjacent_overlap_binary_2_pronoun_para,
                avg_adjacent_overlap_argument_para,
                avg_adjacent_overlap_argument_para_div_seg,
                avg_adjacent_overlap_binary_argument_para,
                avg_adjacent_overlap_2_argument_para,
                avg_adjacent_overlap_2_argument_para_div_seg,
                avg_adjacent_overlap_binary_2_argument_para,
                avg_syn_overlap_sent_noun,
                avg_syn_overlap_sent_verb,
                avg_syn_overlap_para_noun,
                avg_syn_overlap_para_verb,
                avg_lsa_1_all_sent,
                avg_lsa_2_all_sent,
                avg_lsa_1_all_para,
                avg_lsa_2_all_para,
                avg_lda_1_all_sent,
                avg_lda_2_all_sent,
                avg_lda_1_all_para,
                avg_lda_2_all_para,
                avg_word2vec_1_all_sent,
                avg_word2vec_2_all_sent,
                avg_word2vec_1_all_para,
                avg_word2vec_2_all_para,
                avg_basic_connectives,
                avg_conjunctions,
                avg_disjunctions,
                avg_lexical_subordinators,
                avg_coordinating_conjuncts,
                avg_addition,
                avg_sentence_linking,
                avg_the_order,
                avg_reason_and_purpose,
                avg_all_causal,
                avg_positive_causal,
                avg_opposition,
                avg_determiners,
                avg_all_demonstratives,
                avg_attended_demonstratives,
                avg_unattended_demonstratives,
                avg_all_additive,
                avg_all_logical,
                avg_positive_logical,
                avg_negative_logical,
                avg_all_temporal,
                avg_positive_intentional,
                avg_all_positive,
                avg_all_negative,
                avg_all_connective,
                avg_pronoun_density,
                avg_pronoun_noun_ratio,
                avg_repeated_content_lemmas,
                avg_repeated_content_and_pronoun_lemmas
            ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s,%s, %s, %s, %s, %s, %s, %s, %s, %s, %s,%s, %s, %s, %s, %s, %s, %s, %s, %s, %s,%s, %s, %s, %s, %s, %s, %s, %s, %s, %s,%s, %s, %s, %s, %s, %s, %s, %s, %s, %s,%s, %s, %s, %s, %s, %s, %s, %s, %s, %s,%s, %s, %s, %s, %s, %s, %s, %s, %s, %s,%s, %s, %s, %s, %s, %s, %s, %s, %s, %s,%s, %s, %s, %s, %s, %s, %s, %s, %s, %s,%s, %s, %s, %s, %s, %s, %s, %s, %s, %s,%s, %s, %s, %s, %s, %s, %s, %s, %s, %s,%s, %s, %s, %s, %s, %s, %s, %s, %s, %s,%s, %s, %s, %s, %s, %s, %s, %s, %s, %s,%s, %s, %s, %s, %s, %s, %s, %s, %s, %s,%s, %s, %s, %s, %s, %s, %s, %s, %s, %s,%s, %s, %s, %s, %s, %s, %s, %s, %s, %s,%s, %s, %s, %s, %s, %s, %s)
        """
        #177 
        cursor.execute(insert_query, (author_id, *result))
        db.commit()

# Process authors
for author_id_tuple in authors:
    author_id = author_id_tuple[0]
    # Metrics for papers before 2022-11-30
    calculate_and_insert_metrics(author_id, "< '2022-11-30'", "author_metrics_before")
    # Metrics for papers on or after 2022-11-30
    calculate_and_insert_metrics(author_id, ">= '2022-11-30'", "author_metrics_after")

# Close database connection
cursor.close()
db.close()
